CONFIG_MAIN_THREAD_PRIORITY=7
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_SENSOR=n
CONFIG_BMI08X=n

CONFIG_MOTOR=y
CONFIG_MOTOR_DJI=y

CONFIG_CAN=y
CONFIG_CAN_INIT_PRIORITY=80
